### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by kleper** [hackmdio/codimd#1022]
Update the CodiMD code and I have this error:
2018-10-22T02:19:24.871Z - error: uncaughtException: Path must be a string. Received undefined date=Sun Oct 21 2018 21:19:24 GMT-0500 (-05), pid=2919, uid=33, gid=33, cwd=/opt/codimd, execPath=/usr/bin/node, version=v8.12.0, argv=[/usr/bin/node, /opt/codimd/app.js], rss=49569792, heapTotal=23494656, heapUsed=15226464, external=137590, loadavg=[1.2255859375, 1.05859375, 1.47802734375], uptime=4121, trace=[column=11, file=path.js, function=assertPath, line=28, method=null, native=false, column=7, file=path.js, function=Object.resolve, line=1171, method=resolve, native=false, column=24, file=/opt/codimd/lib/config/index.js, function=null, line=181, method=null, native=false, column=30, file=module.js, function=Module._compile, line=653, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=664, method=.js, native=false, column=32, file=module.js, function=Module.load, line=566, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=506, method=null, native=false, column=3, file=module.js, function=Module._load, line=498, method=_load, native=false, column=17, file=module.js, function=Module.require, line=597, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false], stack=[TypeError: Path must be a string. Received undefined,     at assertPath (path.js:28:11),     at Object.resolve (path.js:1171:7),     at Object.<anonymous> (/opt/codimd/lib/config/index.js:181:24),     at Module._compile (module.js:653:30),     at Object.Module._extensions..js (module.js:664:10),     at Module.load (module.js:566:32),     at tryModuleLoad (module.js:506:12),     at Function.Module._load (module.js:498:3),     at Module.require (module.js:597:17),     at require (internal/module.js:11:18)]

**Comment by SISheogorath** [comment]
First of all: You updated CodiMD to what version?

Also: How did you update CodiMD?

The error basically says that whatever you set the variable `viewPath` to, is not a string and this way broken.

I double-checked the defaults and they are fine, so please check your setup.

Maybe you modified some file and used git fogit for updating? I guess you have someone an inconsistent state in your repository. So please either download the latest release as a tar or zip file and only copy your config.json and sequelizerc (and maybe database file) over or use `git reset --hard 1.2.1` (Warning: This may deletes data from the directory so make sure you have a backup!)
