### ISSUE TITLE
CodiMD fails to start with existing unix socket file

### ISSUE THREAD

**Issue by jo-so** [hackmdio/codimd#1024]
When starting CodiMD the first time, it creates the Unix socket (file), but leaves it on shutdown. The second time I start CodiMD, it fails with `message=listen EADDRINUSE /run/codimd/socket, stack=Error: listen EADDRINUSE /run/codimd/socket`. It would be helpful when CodiMD could use an existing socket, because I could set the permissions of the socket and change ownership, before starting CodiMD.

```
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1503:5)
    at startListen (/srv/www/n.jo-so.de/app.js:221:12)
    at /srv/www/n.jo-so.de/app.js:234:47
    at /srv/www/n.jo-so.de/lib/models/revision.js:167:20
    at Model.<anonymous> (/srv/www/n.jo-so.de/lib/models/revision.js:200:41)
    at Model.tryCatcher (/srv/www/n.jo-so.de/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/www/n.jo-so.de/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/srv/www/n.jo-so.de/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/srv/www/n.jo-so.de/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/srv/www/n.jo-so.de/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/srv/www/n.jo-so.de/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/srv/www/n.jo-so.de/node_modules/bluebird/js/release/async.js:131:9), code=EADDRINUSE, errno=EADDRINUSE, syscall=listen, address=/run/codimd/socket, port=-1
```

@ahihi, please have a look.

**Comment by ahihi** [comment]
correct me if i'm wrong, but i don't think it's possible to reuse a unix socket?

i guess we could detect the existing one, delete it, and create a new one with the same permissions etc. or maybe just specify the permissions in the config.

**Comment by SISheogorath** [comment]
@ahihi standard way to do it is to call `unlink` on the socket before binding it and/or calling it on exit.

See: https://github.com/hackmdio/codimd/blob/152dfc23230c2575633a0321c855f37fcc50fb96/app.js#L250-L273

**Comment by naimo** [comment]
I have the same problem.
@SISheogorath the piece of code you quote doesn't seem to call `unlink`, am I missing something ?

To test, I added `fs.unlink(config.path)` in that function and it seems to do the trick. Though I have no idea what is the proper way to do.

**Comment by SISheogorath** [comment]
@naimo sounds great, I guess the HackMD team will welcome this contribution.

If you want to provide it to CodiMD as well, feel free to contribute is to https://github.com/codimd/server
