### ISSUE TITLE
Under docker env image upload type minio failing

### ISSUE THREAD

**Issue by r2k** [hackmdio/codimd#1044]
Hi,

I am trying to run codimd in docker, I followed guidelines from below link 

- https://github.com/hackmdio/codimd-container
- https://github.com/hackmdio/codimd/blob/master/docs/guides/minio-image-upload.md

For "CMD_IMAGE_UPLOAD_TYPE" imgur & filesystem its working type, but for "minio"
I stuck with below error.

```
app_1_565dcdd3e1e9 | 2018-11-08T14:21:40.743Z - info: 10.0.2.2 - - [08/Nov/2018:14:21:40 +0000] "GET /me HTTP/1.1" 304 - "http://127.0.0.1:3000/aZIidA5MQta8uNjhKWnRWw" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Vivaldi/2.1.1337.36"
app_1_565dcdd3e1e9 | 
app_1_565dcdd3e1e9 | 2018-11-08T14:21:56.801Z - info: deserializeUser: f9341c86-cc07-486e-8500-64dcaedf62a7
app_1_565dcdd3e1e9 | 2018-11-08T14:21:56.973Z - error:  Error: Error: connect ECONNREFUSED 127.0.0.1:9000
app_1_565dcdd3e1e9 |     at /hackmd/lib/web/imageRouter/minio.js:40:18
app_1_565dcdd3e1e9 |     at ObjectUploader.<anonymous> (/hackmd/node_modules/minio/dist/main/object-uploader.js:55:7)
app_1_565dcdd3e1e9 |     at emitOne (events.js:121:20)
app_1_565dcdd3e1e9 |     at ObjectUploader.emit (events.js:211:7)
app_1_565dcdd3e1e9 |     at onwriteError (_stream_writable.js:417:12)
app_1_565dcdd3e1e9 |     at onwrite (_stream_writable.js:439:5)
app_1_565dcdd3e1e9 |     at ObjectUploader.afterTransform (_stream_transform.js:90:3)
app_1_565dcdd3e1e9 |     at /hackmd/node_modules/minio/dist/main/object-uploader.js:84:25
app_1_565dcdd3e1e9 |     at _makeRequest (/hackmd/node_modules/minio/dist/main/minio.js:382:21)
app_1_565dcdd3e1e9 |     at /hackmd/node_modules/minio/dist/main/minio.js:485:16
app_1_565dcdd3e1e9 |     at ClientRequest.<anonymous> (/hackmd/node_modules/minio/dist/main/minio.js:425:9)
app_1_565dcdd3e1e9 |     at emitOne (events.js:121:20)
app_1_565dcdd3e1e9 |     at ClientRequest.emit (events.js:211:7)
app_1_565dcdd3e1e9 |     at Socket.socketErrorListener (_http_client.js:387:9)
app_1_565dcdd3e1e9 |     at emitOne (events.js:116:13)
app_1_565dcdd3e1e9 |     at Socket.emit (events.js:211:7)
app_1_565dcdd3e1e9 | 2018-11-08T14:21:57.055Z - info: 10.0.2.2 - - [08/Nov/2018:14:21:57 +0000] "POST /uploadimage HTTP/1.1" 500 - "http://127.0.0.1:3000/aZIidA5MQta8uNjhKWnRWw?both" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Vivaldi/2.1.1337.36"
app_1_565dcdd3e1e9 | 
^CGracefully stopping... (press Ctrl+C again to force)
Stopping codimd-container_app_1_565dcdd3e1e9      ... done
Stopping codimd-container_database_1_c73980818236 ... done
```

I am able to access "minio" via web & mc client, and I am using same working secret & access key in docker conf ...

```
  app:
    # Uncomment the following section to build the image yourself:
    #build:
    #  context: .
    #  dockerfile: debian/Dockerfile
    #  args:
    #    - "VERSION=master"
    #    - "CODIMD_REPOSITORY=https://github.com/hackmdio/codimd.git"
    image: hackmdio/hackmd:1.2.1

    environment:
      - CMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
      - CMD_IMAGE_UPLOAD_TYPE=minio
      - CMD_MINIO_ACCESS_KEY="XXXXXXXXXXXXX"
      - CMD_MINIO_SECRET_KEY="iYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
      - CMD_MINIO_ENDPOINT=127.0.0.1
      - CMD_MINIO_PORT=9000
      - CMD_MINIO_SECURE=false
      - CMD_S3_BUCKET=hackmd

```

Plz let me know what I am making wrong here ...

**Comment by SISheogorath** [comment]
Your endpoint is probably not 127.0.0.1.

Container use network namespaces to isolate the applications from each other. This means that each container has an own `lo` device. Which leads to the answer: `127.0.0.1` in your CodiMD container is not the same `127.0.0.1` as on your host and not the same `127.0.0.1` as in your minio container.

So just use the public name DNS name of your minio instance (it needs to be accessible for your users anyway) to upload your images there.
