### ISSUE TITLE
OAUTH GIThub and Twitter

### ISSUE THREAD

**Issue by kleper** [hackmdio/codimd#1050]
Despues de actualizar mi instancia (docutopia.tupale.co) a la ultima versión tengo este error con los oauth de GitHub y Twitter

GITHUB:
AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.
    at Strategy.OAuth2Strategy.authenticate (/opt/codimd/node_modules/passport-oauth2/lib/strategy.js:131:25)
    at attempt (/opt/codimd/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/opt/codimd/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/opt/codimd/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/codimd/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/codimd/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/codimd/node_modules/express/lib/router/layer.js:95:5)
    at /opt/codimd/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/codimd/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/codimd/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/opt/codimd/node_modules/express/lib/router/index.js:174:3)
    at router (/opt/codimd/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/opt/codimd/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/codimd/node_modules/express/lib/router/index.js:317:13)
    at /opt/codimd/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/codimd/node_modules/express/lib/router/index.js:335:12)

Twitter:
Error: Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings
    at Strategy.parseErrorResponse (/opt/codimd/node_modules/passport-twitter/lib/strategy.js:206:12)
    at Strategy.OAuthStrategy._createOAuthError (/opt/codimd/node_modules/passport-oauth1/lib/strategy.js:393:16)
    at /opt/codimd/node_modules/passport-oauth1/lib/strategy.js:244:41
    at /opt/codimd/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/opt/codimd/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/opt/codimd/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

I think it is something related to the configuration of each of the services, but I have already reviewed them and they are configured as they should be.

**Comment by kleper** [comment]
I solved it, I forgot in the configuration to write the domain in which my instance of CODIMD works
