### ISSUE TITLE
A bug when upload image using filesystem (url.resolve)

### ISSUE THREAD

**Issue by ssst0n3** [hackmdio/codimd#1102]
There's a bug about image uploading.
I'm not familiar with nodejs, but i fixed it on my laptap.

When i upload an image, i meet this exception:
```
2018-12-17T15:08:28.343Z error: 	uncaughtException: url.URL.resolve is not a function
TypeError: url.URL.resolve is not a function
    at Object.exports.uploadImage (/codimd/lib/web/imageRouter/filesystem.js:19:26)
    at /codimd/lib/web/imageRouter/index.js:31:22
    at IncomingForm.<anonymous> (/codimd/node_modules/formidable/lib/incoming_form.js:107:9)
    at emitNone (events.js:106:13)
    at IncomingForm.emit (events.js:208:7)
    at IncomingForm._maybeEnd (/codimd/node_modules/formidable/lib/incoming_form.js:557:8)
    at /codimd/node_modules/formidable/lib/incoming_form.js:238:12
    at WriteStream.<anonymous> (/codimd/node_modules/formidable/lib/file.js:79:5)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:613:14)
    at afterWrite (_stream_writable.js:464:3)
    at onwrite (_stream_writable.js:454:7)
    at fs.write (fs.js:2194:5)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:685:5)
```

I replace the `url.URL.resolve` by `url.resolve`  in /codimd/lib/web/imageRouter/filesystem.js:19:26

Then i can upload successfully.

codimd is wonderful, thank you. hopefully you will fix it.

**Comment by ccoenen** [comment]
Hi @ssst0n3, thanks for reporting this issue!

May I ask what your node.js version is? The `url.resolve` has been marked as deprecated in Node 11, which is why we moved to `url.URL`. That should be in node 6.13 (and later). If your version is older than either of those, I would strongly recommend updating. Node 6 is currently at version 6.15, and support for node 6 will drop in april (node.js itself won't be maintained any more which is why we will also stop testing on that platform).

You can (usually) find out what your node.js version is by typing `node --version` into your shell.

**Comment by ccoenen** [comment]
If you're on debian 9 ("Stretch") or Ubuntu 16.04 LTS, and installed node.js from their system default packages you will most likely run node 4.x.

**Comment by SISheogorath** [comment]
@ssst0n3 if you want to check #1103, this should fix it.
