### ISSUE TITLE
PDF download crashes heroku app

### ISSUE THREAD

**Issue by ldub** [hackmdio/codimd#1129]
When I download as PDF, the heroku app crashes with the following log:

```
2019-01-24T20:24:02.982008+00:00 app[web.1]: 2019-01-24T20:24:02.981Z info: 	deserializeUser: e16a5f5c-ch4i-sa98-shj8-45d1270624eb
2019-01-24T20:24:03.007384+00:00 app[web.1]: 2019-01-24T20:24:03.007Z info: 	0.0.0.0 - - [24/Jan/2019:20:24:03 +0000] "GET /me HTTP/1.1" 304 - "http://host.notarealurl.io/features" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/0.0.0.0 Safari/537.36"
2019-01-24T20:24:03.007389+00:00 app[web.1]:
2019-01-24T20:24:06.097113+00:00 app[web.1]: 2019-01-24T20:24:06.096Z info: 	deserializeUser: e16a5f5c-ch4i-sa98-shj8-45d1270624eb
2019-01-24T20:24:09.357799+00:00 app[web.1]: 2019-01-24T20:24:09.357Z error: 	uncaughtException: Callback must be a function
2019-01-24T20:24:09.390275+00:00 heroku[router]: at=info method=GET path= "/socket.io/?noteId= features&EIO= 3&transport= websocket&sid=dDSFcwGhBHfwyGEBAAAA" host=host.notarealurl.io request_id=f37541cc-a7d2-4f64-9e9a-05c23c1b15ed fwd="0.0.0.0" dyno=web.1 connect=0ms service=8831ms status=101 bytes=175 protocol=http
2019-01-24T20:24:09.357812+00:00 app[web.1]: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
2019-01-24T20:24:09.357814+00:00 app[web.1]: at makeCallback (fs.js:142:11)
2019-01-24T20:24:09.357816+00:00 app[web.1]: at Object.unlink (fs.js:960:14)
2019-01-24T20:24:09.357818+00:00 app[web.1]: at /app/lib/response.js:323:8
2019-01-24T20:24:09.357820+00:00 app[web.1]: at /app/node_modules/stream-from-to/node_modules/async/lib/async.js:726:13
2019-01-24T20:24:09.357822+00:00 app[web.1]: at /app/node_modules/stream-from-to/node_modules/async/lib/async.js:52:16
2019-01-24T20:24:09.357824+00:00 app[web.1]: at done (/app/node_modules/stream-from-to/node_modules/async/lib/async.js:246:17)
2019-01-24T20:24:09.357826+00:00 app[web.1]: at /app/node_modules/stream-from-to/node_modules/async/lib/async.js:44:16
2019-01-24T20:24:09.357827+00:00 app[web.1]: at /app/node_modules/stream-from-to/node_modules/async/lib/async.js:723:17
2019-01-24T20:24:09.357829+00:00 app[web.1]: at /app/node_modules/stream-from-to/node_modules/async/lib/async.js:167:37
2019-01-24T20:24:09.357831+00:00 app[web.1]: at WriteStream.<anonymous> (/app/node_modules/stream-from-to/index.js:99:41)
2019-01-24T20:24:09.357832+00:00 app[web.1]: at WriteStream.emit (events.js:188:13)
2019-01-24T20:24:09.357834+00:00 app[web.1]: at finishMaybe (_stream_writable.js:646:14)
2019-01-24T20:24:09.357835+00:00 app[web.1]: at stream._final (_stream_writable.js:624:5)
2019-01-24T20:24:09.357837+00:00 app[web.1]: at WriteStream._final (internal/fs/streams.js:270:3)
2019-01-24T20:24:09.357839+00:00 app[web.1]: at callFinal (_stream_writable.js:617:10)
2019-01-24T20:24:09.357840+00:00 app[web.1]: at processTicksAndRejections (internal/process/next_tick.js:76:17)
2019-01-24T20:24:09.358849+00:00 app[web.1]: 2019-01-24T20:24:09.358Z error: 	An uncaught exception has occured.
2019-01-24T20:24:09.359197+00:00 app[web.1]: 2019-01-24T20:24:09.359Z error: 	Callback must be a function
2019-01-24T20:24:09.359343+00:00 app[web.1]: 2019-01-24T20:24:09.359Z error: 	Process will exit now.
2019-01-24T20:24:09.406279+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-01-24T20:24:09.407057+00:00 app[web.1]: npm ERR! errno 1
2019-01-24T20:24:09.409831+00:00 app[web.1]: npm ERR! CodiMD@1.2.1 start: `sequelize db:migrate && node app.js`
2019-01-24T20:24:09.410188+00:00 app[web.1]: npm ERR! Exit status 1
2019-01-24T20:24:09.410825+00:00 app[web.1]: npm ERR!
2019-01-24T20:24:09.411102+00:00 app[web.1]: npm ERR! Failed at the CodiMD@1.2.1 start script.
2019-01-24T20:24:09.411562+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-01-24T20:24:09.445429+00:00 app[web.1]:
2019-01-24T20:24:09.446999+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-01-24T20:24:09.447473+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-01-24T20_24_09_415Z-debug.log
2019-01-24T20:24:09.388767+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/features/pdf" host=host.notarealurl.io request_id=10f4eb0e-9b2a-4eb9-b8b0-303bfc710052 fwd="0.0.0.0" dyno=web.1 connect=1ms service=3314ms status=503 bytes=0 protocol=http
2019-01-24T20:24:09.529702+00:00 heroku[web.1]: Process exited with status 1
2019-01-24T20:24:09.550966+00:00 heroku[web.1]: State changed from up to crashed
```

This looks like it could be a duplicate of #931, however on Heroku I don't have the freedom of reinstalling a package or switching my version of node manually.

Somebody mentioned that this happened until they switched to Node 8, perhaps the `engines` block in [package.json](https://github.com/hackmdio/codimd/blob/master/package.json#L139) needs to specify node 8?

**Comment by SISheogorath** [comment]
I already noticed: https://github.com/hackmdio/codimd/pull/1127

We'll merge that later
