### ISSUE TITLE
npm run build – Exit errno 1

### ISSUE THREAD

**Issue by FirePowi** [hackmdio/codimd#1141]
`$ node --version
v8.11.4

$npm -version
6.7.0`

Logs : 
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.7.0
3 info using node@v8.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle CodiMD@1.2.1~prebuild: CodiMD@1.2.1
6 info lifecycle CodiMD@1.2.1~build: CodiMD@1.2.1
7 verbose lifecycle CodiMD@1.2.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle CodiMD@1.2.1~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/codimd/codimd-master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle CodiMD@1.2.1~build: CWD: /home/codimd/codimd-master
10 silly lifecycle CodiMD@1.2.1~build: Args: [ '-c',
10 silly lifecycle   'webpack --config webpack.prod.js --progress --colors --bail' ]
11 silly lifecycle CodiMD@1.2.1~build: Returned: code: 1  signal: null
12 info lifecycle CodiMD@1.2.1~build: Failed to exec build script
13 verbose stack Error: CodiMD@1.2.1 build: `webpack --config webpack.prod.js --progress --colors --bail`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid CodiMD@1.2.1
15 verbose cwd /home/codimd/codimd-master
16 verbose Linux 3.16.0-5-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v8.11.4
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error CodiMD@1.2.1 build: `webpack --config webpack.prod.js --progress --colors --bail`
22 error Exit status 1
23 error Failed at the CodiMD@1.2.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]```

**Comment by SISheogorath** [comment]
Can't really reproduce, can you try to build it with our container image? https://github.com/hackmdio/codimd-container

Also did you run `npm install` before? Tried to remote the `node_modules` folder before updating?

**Comment by ccoenen** [comment]
Also: feel free to drop by in [the matrix channel](https://riot.im/app/#/room/#codimd:matrix.org). This might be something where a lot of back and forth is neccessary to find the bug if we can't get it to do the same on our machines.

**Comment by FirePowi** [comment]
I used docker. It worked.

**Comment by ccoenen** [comment]
I'm closing this. If you have any further questions, please feel free to reach out via this issue tracker or on the matrix channel!
