### ISSUE TITLE
Imagedata pasting fails with invalid URL error

### ISSUE THREAD

**Issue by MartB** [hackmdio/codimd#1147]
Error log:
```
Feb 14 15:43:28 martb-server npm[16212]: 2019-02-14T14:43:28.688Z error:        uncaughtException: Invalid URL: /uploads/
Feb 14 15:43:28 martb-server npm[16212]: TypeError [ERR_INVALID_URL]: Invalid URL: /uploads/
Feb 14 15:43:28 martb-server npm[16212]:     at onParseError (internal/url.js:240:17)
Feb 14 15:43:28 martb-server npm[16212]:     at parse (internal/url.js:249:3)
Feb 14 15:43:28 martb-server npm[16212]:     at new URL (internal/url.js:324:5)
Feb 14 15:43:28 martb-server npm[16212]:     at new URL (internal/url.js:322:14)
Feb 14 15:43:28 martb-server npm[16212]:     at Object.exports.uploadImage (/opt/hackmd/lib/web/imageRouter/filesystem.js:19:19)
Feb 14 15:43:28 martb-server npm[16212]:     at /opt/hackmd/lib/web/imageRouter/index.js:31:22
Feb 14 15:43:28 martb-server npm[16212]:     at IncomingForm.<anonymous> (/opt/hackmd/node_modules/formidable/lib/incoming_form.js:107:9)
Feb 14 15:43:28 martb-server npm[16212]:     at IncomingForm.emit (events.js:182:13)
Feb 14 15:43:28 martb-server npm[16212]:     at IncomingForm._maybeEnd (/opt/hackmd/node_modules/formidable/lib/incoming_form.js:557:8)
Feb 14 15:43:28 martb-server npm[16212]:     at /opt/hackmd/node_modules/formidable/lib/incoming_form.js:238:12
Feb 14 15:43:28 martb-server npm[16212]:     at WriteStream.<anonymous> (/opt/hackmd/node_modules/formidable/lib/file.js:79:5)
Feb 14 15:43:28 martb-server npm[16212]:     at Object.onceWrapper (events.js:273:13)
Feb 14 15:43:28 martb-server npm[16212]:     at WriteStream.emit (events.js:182:13)
Feb 14 15:43:28 martb-server npm[16212]:     at finishMaybe (_stream_writable.js:641:14)
Feb 14 15:43:28 martb-server npm[16212]:     at stream._final (_stream_writable.js:619:5)
Feb 14 15:43:28 martb-server npm[16212]:     at WriteStream._final (internal/fs/streams.js:264:3)
Feb 14 15:43:28 martb-server npm[16212]: 2019-02-14T14:43:28.688Z error:        An uncaught exception has occured.
Feb 14 15:43:28 martb-server npm[16212]: 2019-02-14T14:43:28.688Z error:        Invalid URL: /uploads/
Feb 14 15:43:28 martb-server npm[16212]: 2019-02-14T14:43:28.688Z error:        Process will exit now.
```

I would assume my `config.serverURL` is empty somehow, but i dont know why that is.

Running on the latest master

**Comment by MartB** [comment]
Scratch that, as a matter of fact i missed the following warning message,
https://github.com/hackmdio/codimd/blame/f9cc2ff0ef56aa5f0a655f9209321460748ba621/lib/config/index.js#L104

so if someone stumbles upon the same issue as me, just add the domain to your config.

**Comment by MartB** [comment]
Scratch that, as a matter of fact i missed the following warning message,
https://github.com/hackmdio/codimd/blame/f9cc2ff0ef56aa5f0a655f9209321460748ba621/lib/config/index.js#L104

so if someone stumbles upon the same issue as me, just add the domain to your config.
