### ISSUE TITLE
Uncaught exception with phantomjs when exporting PDF

### ISSUE THREAD

**Issue by ajanvier** [hackmdio/codimd#1182]
Hi, I've been having this issue with CodiMD 1.3.0 and I thought it would be fixed in 1.3.1 by seeing `Fix broken PDF export` in the changelog but it appears it is still present.

The following error shows up in my logs whenever I try to use the Export to PDF feature.

**CodiMD Version:** 1.3.1
**Docker image:** 1.3.1-alpine with `CMD_ALLOW_PDF_EXPORT=true`
**Docker version:** 18.09.3

```
2019-03-26T11:43:22.386Z error:         uncaughtException: spawn /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
Error: spawn /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2019-03-26T11:43:22.387Z error:         An uncaught exception has occured.
2019-03-26T11:43:22.387Z error:         spawn /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
2019-03-26T11:43:22.387Z error:         Process will exit now.
```

Thank you for you help.

**Comment by SISheogorath** [comment]
@ajanvier PDF export is not possible in alpine since the rendering engine used by phantomjs is not compiling with musl-lib.

This is not intended to work. you can use the debian-based image, when you like to use the PDF export feature

**Comment by ajanvier** [comment]
Oh thanks @SISheogorath, now I see it's written into the alpine's container Dockerfile.
Wouldn't it be useful to write it in the main README so other people don't reproduce the same mistake ?
