### ISSUE TITLE
Error when i will start hackmd after a server restart

### ISSUE THREAD

**Issue by radeartz** [hackmdio/codimd#1229]
`2019-06-27T18:27:26.158Z warn:  Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
2019-06-27T18:27:26.166Z warn:  Session secret not set. Using random generated one. Please set `sessionSecret` in your config.js file. All users will be logged out.
2019-06-27T18:27:27.066Z error:         uncaughtException: Please install sqlite3 package manually
Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/var/www/codimd/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/var/www/codimd/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)
    at new SqliteDialect (/var/www/codimd/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/var/www/codimd/node_modules/sequelize/lib/sequelize.js:241:20)
    at Object.<anonymous> (/var/www/codimd/lib/models/index.js:23:15)
    at Module._compile (internal/modules/cjs/loader.js:779:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:790:10)
    at Module.load (internal/modules/cjs/loader.js:642:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:682:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/var/www/codimd/lib/response.js:15:14)
    at Module._compile (internal/modules/cjs/loader.js:779:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:790:10)
    at Module.load (internal/modules/cjs/loader.js:642:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:682:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/var/www/codimd/app.js:25:16)
    at Module._compile (internal/modules/cjs/loader.js:779:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:790:10)
    at Module.load (internal/modules/cjs/loader.js:642:32)
`

**Comment by jackycute** [comment]
Hi @radeartz you will need to specify config file or environment variables, or the server won't be able to connect DB.
See more here:
https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-configuration

**Comment by jackycute** [comment]
Hi @radeartz did you try setup the config?

**Comment by jackycute** [comment]
Close for now, feel free to reopen if you found anything.
