### ISSUE TITLE
npm run build - Exit errno 137

### ISSUE THREAD

**Issue by pyrochlore** [hackmdio/codimd#1254]
node -v
v10.16.0
npm -v
6.9.0

I followed the [document ](https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-manual-deployment). While running 'npm run build', the messages are
```
> codimd@1.3.1 build /home/XXX/codimd
> webpack --config webpack.prod.js --progress --colors --bail

96% [0] chunk asset optimization TerserPlugin <--the process stuck here for a long time
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! codimd@1.3.1 build: `webpack --config webpack.prod.js --progress --colors --bail`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the codimd@1.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /XXX/.npm/_logs/YYYYYYY-debug.log
```
The log file is shown as following:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle codimd@1.3.1~prebuild: codimd@1.3.1
6 info lifecycle codimd@1.3.1~build: codimd@1.3.1
7 verbose lifecycle codimd@1.3.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle codimd@1.3.1~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/XXX/codimd/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle codimd@1.3.1~build: CWD: /home/XXX/codimd
10 silly lifecycle codimd@1.3.1~build: Args: [ '-c',
10 silly lifecycle   'webpack --config webpack.prod.js --progress --colors --bail' ]
11 silly lifecycle codimd@1.3.1~build: Returned: code: 137  signal: null
12 info lifecycle codimd@1.3.1~build: Failed to exec build script
13 verbose stack Error: codimd@1.3.1 build: `webpack --config webpack.prod.js --progress --colors --bail`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid codimd@1.3.1
15 verbose cwd /home/XXX/codimd
16 verbose Linux 4.15.0-55-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 137
22 error codimd@1.3.1 build: `webpack --config webpack.prod.js --progress --colors --bail`
22 error Exit status 137
23 error Failed at the codimd@1.3.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**Comment by pyrochlore** [comment]
The error is not shown anymore after I added memory up to 2GB to my server.

**Comment by harrypotter0409** [comment]
Hi pyrochlore
I got the same error now.
Where can I add memory up to my server?

**Comment by aalok-yadav** [comment]
First, you will have to remove the npm cache and upgrade to the latest version of the node and npm will resolve the issue.

`sudo npm cache clean -f`
`sudo npm install -g n install n `
`sudo n stable `

The first command will force clean the npm package manager's cache, After the second and third commands, a stable version of the node and npm will be installed. then you can execute **npm i** and **npm run build** for creating an optimized production build.

This solution worked for the same error on the **npm run build** command in nextjs.
