### ISSUE TITLE
[BUG] manage_users tries to use SQLite even if config.json has postgres setup

### ISSUE THREAD

**Issue by Lana-chan** [hackmdio/codimd#1280]
trying to add an user to a hosted codimd with registration disabled, but it gives me an sqlite error:

```erin@localhost /s/c/server> bin/manage_users --pass fakepass --add fake@example.com
(node:10680) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: SQLITE_ERROR: no such table: Users
    at Query.formatError (/srv/codimd/server/node_modules/sequelize/lib/dialects/sqlite/query.js:419:16)
    at Query._handleQueryResponse (/srv/codimd/server/node_modules/sequelize/lib/dialects/sqlite/query.js:73:18)
    at afterExecute (/srv/codimd/server/node_modules/sequelize/lib/dialects/sqlite/query.js:247:31)
    at Statement.errBack (/srv/codimd/server/node_modules/sqlite3/lib/sqlite3.js:16:21)
(node:10680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

i have the postgres db set up in `config.json` and `.sequelizerc` properly, the web interface works fine and i was able to register an user if i re-enabled email registration, but not through the command line.

**Comment by Lana-chan** [comment]
after much racking my brain against this issue, i realized the problem was the lack of an environment variable:
`erin@localhost /s/c/server> env NODE_ENV=production bin/manage_users --pass fakepass --add fake@example.com`
it would be useful to point this out somewhere in the documentation. i will leave the issue open for further discussion on that but my problem has been resolved
