### ISSUE TITLE
(GitLab) OAuth doesn't use proxy (variable)

### ISSUE THREAD

**Issue by rhtenhove** [hackmdio/codimd#1295]
I'd like to use an internal (corporate) GitLab server as an OAuth provider. It can only be reached by the CodiMD server through an http(s)-proxy. The OAuth handshake fails when trying to obtain an access token, which means it doesn't use the proxy to access the GitLab server.

The proxy is set using the `http_proxy` and `https_proxy` variables, but these apparently are ignored, causing the request to fail. A look with `tcpdump` reveals that indeed it tries to make a direct connection to the internal gitlab server, which is not possible.

```
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/codimd/node_modules/passport-oauth2/lib/strategy.js:408:17)
    at /codimd/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /codimd/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/codimd/node_modules/oauth/lib/oauth2.js:162:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2019-10-08T12:25:51.479Z info:  172.20.0.4 - - [08/Oct/2019:12:25:51 +0000] "GET /auth/gitlab/callback?code=alongstringresemblingthecode HTTP/1.1" 500 148 "https://internal.gitlab.domain/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.93 Safari/537.36 Vivaldi/2.8.1664.40"
```

How might this be resolved?

**Comment by jackycute** [comment]
Hi @rhtenhove,

I don't quite get it, could you explain more about the proxy?
I searched a bit, maybe you mean this?
https://github.com/jaredhanson/passport-oauth2/issues/59#issuecomment-279304518

**Comment by rhtenhove** [comment]
That is indeed what I mean. As far as I can see this has never been implemented in the passport-oauth2 package.

Do you have a suggestion on how this could become part of codimd?

**Comment by jackycute** [comment]
I afraid this will require to modify current OAuth strategy to do so.
The corresponding gitlab oauth usage is here: https://github.com/hackmdio/codimd/blob/develop/lib/web/auth/gitlab/index.js

**Comment by rhtenhove** [comment]
I've added the required code, based on [this](https://github.com/jaredhanson/passport-oauth2/issues/59#issuecomment-279304518), and successfully tested it on my server. I've created a pull request with the added code: #1296
