### ISSUE TITLE
CodiMD fails with phantomjs ENOENT

### ISSUE THREAD

**Issue by jakubgs** [hackmdio/codimd#1298]
My instance of CodiMD has crashed 3 times in the past few days due to the following error:
```
info: #011deserializeUser: 38118208-b081-4b7a-b49a-d6ded20723a9
error: #011uncaughtException: spawn /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
Error: spawn /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
error: #011An uncaught exception has occured.
error: #011spawn /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
error: #011Process will exit now.
```
I'm running a Docker container image `hackmdio/hackmd:1.3.1-alpine`.

I check on the container itself the file is there and looks fine:
```
 % docker run --rm -it --entrypoint=sh hackmdio/hackmd:1.3.1-alpine
/codimd # ls -l /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
-rwxr-xr-x    1 root     root      67932064 Mar 26  2019 /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
```
BUT when I try to run it I get back:
```
/codimd # /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --version
sh: /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: not found
```
But according to `stat` the file is just fine:
```
/codimd # stat /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
  File: /codimd/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
  Size: 67932064  	Blocks: 132680     IO Block: 4096   regular file
Device: 8fh/143d	Inode: 4927242     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-03-26 22:07:41.000000000
Modify: 2019-03-26 22:07:41.000000000
Change: 2019-04-23 07:30:46.000000000
```
Which makes no sense whatsoever.

I might add that the error doesn't coincide with any CPU or memory usage spike at all.

**Comment by jackycute** [comment]
Hi @jakubgs,
This crash was caused by PDF export, it would require phantomjs to be installed and it's not in the alpine based docker image.

Please change to the image to `hackmdio/hackmd:1.3.1` and it will support PDF export.

**Comment by jakubgs** [comment]
Oh yeah, you're absolutely right. I switched to using the `hackmdio/hackmd:1.3.1` image instead of the Alpine Linux one and it works just fine, no more PhantomJS errors. Thank you!
