### ISSUE TITLE
missing mysql2 package on v1.4.0

### ISSUE THREAD

**Issue by Gingfrederik** [hackmdio/codimd#1356]
Hi 
I got this error message while starting v1.4.0 of codimd
it seems to be missing the mysql2 package for sequelize
```
2019-11-28T02:46:42.305Z warn:  Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
2019-11-28T02:46:42.307Z warn:  Session secret not set. Using random generated one. Please set `sessionSecret` in your config.js file. All users will be logged out.
2019-11-28T02:46:42.541Z error:         uncaughtException: Please install mysql2 package manually
Error: Please install mysql2 package manually
    at ConnectionManager._loadDialectModule (/Users/jefferson/Documents/codimd/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/Users/jefferson/Documents/codimd/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:28:21)
    at new MysqlDialect (/Users/jefferson/Documents/codimd/node_modules/sequelize/lib/dialects/mysql/index.js:14:30)
    at new Sequelize (/Users/jefferson/Documents/codimd/node_modules/sequelize/lib/sequelize.js:320:20)
    at Object.<anonymous> (/Users/jefferson/Documents/codimd/lib/models/index.js:23:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jefferson/Documents/codimd/lib/response.js:15:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jefferson/Documents/codimd/app.js:24:16)
    at Module._compile (module.js:653:30)
```

**Comment by a60814billy** [comment]
Hi @Gingfrederik,
Thanks for reporting this issue.
We'll fixed in 1.4.1, and will release new version in the next few days!
