### ISSUE TITLE
Can I use just use `node ./codimd` to run the server ?

### ISSUE THREAD

**Issue by beppe9000** [hackmdio/codimd#1364]
I wonder if that is sufficient to run in production mode. How do I set it in the config if needed ?

**Comment by jackycute** [comment]
Hi @beppe9000,
Please take a look at the documentation: https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-manual-deployment

**Comment by beppe9000** [comment]
I get this in apache logs:

```
Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
    at Module.require (/opt/cpanel/ea-ruby24/root/usr/share/passenger/helper-scripts/node-loader.js:63:12)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/segniass/web/.node_js_apps/codimd/node_modules/shortid/lib/util/cluster-worker-id.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.require (/opt/cpanel/ea-ruby24/root/usr/share/passenger/helper-scripts/node-loader.js:80:25)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/segniass/web/.node_js_apps/codimd/node_modules/shortid/lib/index.js:11:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.require (/opt/cpanel/ea-ruby24/root/usr/share/passenger/helper-scripts/node-loader.js:80:25)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/segniass/web/.node_js_apps/codimd/node_modules/shortid/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

**Comment by a60814billy** [comment]
If you want to use apache to serve codimd, please use reverse proxy setting.
Do not running codimd with `Passenger`, we doesn't support this deployment method.

**Comment by beppe9000** [comment]
Is shortid the only place where the node cluster dependency is introduced ?

**Comment by beppe9000** [comment]
Is there a way to use https everywhere in the frontend ?

**Comment by jackycute** [comment]
> Is there a way to use https everywhere in the frontend ?

Yes, please follow the documentation: https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-configuration
Set `CMD_PROTOCOL_USESSL=true` will force https protocol for all resources, at same time, please specify `CMD_DOMAIN` to make this work.

**Comment by beppe9000** [comment]
I was thinking it would also enable ssl endpoint so i set that to false since the reverse proxy does ssl but now it's clear they are independent settings. Thanks.
<hr>
The last problem is that despite everything working now that I switched from a subdirectory to a subdomain I get this error in firefox which I  think it's failure to connecto to websocket securely

`Firefox can’t establish a connection to the server at wss://pad.001-me.com.eu/socket.io/?noteId=NqYBatXEQN-x8CozQCxwLA&EIO=3&transport=websocket&sid=xf-MEnlN-tnZF0KgAAAs. `

**Comment by jackycute** [comment]
This is more about the wss or SSL proxy config, closing for now.
