### ISSUE TITLE
Improve file base database config & documentation

### ISSUE THREAD

**Issue by Yukaii** [hackmdio/codimd#1396]
When running `sequelize db:migrate`, sequelize-cli takes `.sequelizerc`'s config, but in our `.sequelizerc.example`:

```js
module.exports = {
  config: path.resolve('config.json'),
  'migrations-path': path.resolve('lib', 'migrations'),
  'models-path': path.resolve('lib', 'models'),
  url: process.env['CMD_DB_URL'] || config.dbURL
}
```

`config: path.resolve('config.json')` this line never works because sequelize `config.json` should be in the [following format](https://sequelize.org/master/manual/migrations.html#configuration):

```json
{
  "development": {
    "username": "root",
    "password": null,
    ...
  }
}
```

But in our `config.json.example`:

```json
  "development": {
    "db": {
      "username": "root",
      "password": null,
      ...
    }
  }
```

Developers need to set `dbURL` in config.json in order not to write it twice:

```json
{
  "development": {
    "dbURL": "postgres://localhost:5432/codimd",
    ...
  }
}
```

**Comment by MHajoha** [comment]
This is causing problems for me as well. I've been looking for a solution and have come across two possibilities:

1. Don't use the Sequelize CLI for migrations at all. There is [Umzug](https://github.com/sequelize/umzug), which provides a programmatic way to migrate databases. Unfortunately, I am unable to run the `20180525153000-user-add-delete-token.js` migration with it, as Umzug drops and recreates the Users table with `deleteToken` already present in `20180326103000-use-text-in-tokens.js`.
    <details>
    <summary>Failed migration logs</summary>

    ```
    ...
    2020-07-07T00:00:18.013Z debug: 	== 20180326103000-use-text-in-tokens: migrating =======
    2020-07-07T00:00:18.014Z debug: 	Executing (default): PRAGMA TABLE_INFO(`Users`);
    2020-07-07T00:00:18.014Z debug: 	Executing (default): CREATE TABLE IF NOT EXISTS `Users_backup` (`id` UUID PRIMARY KEY, `profileid` VARCHAR(255), `profile` TEXT, `history` TEXT, `accessToken` TEXT, `refreshToken` TEXT, `deleteToken` UUID, `email` TEXT, `password` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
    2020-07-07T00:00:18.015Z debug: 	Executing (default): INSERT INTO `Users_backup` SELECT `id`, `profileid`, `profile`, `history`, `accessToken`, `refreshToken`, `deleteToken`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users`;
    2020-07-07T00:00:18.015Z debug: 	Executing (default): DROP TABLE `Users`;
    2020-07-07T00:00:18.015Z debug: 	Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`id` UUID PRIMARY KEY, `profileid` VARCHAR(255), `profile` TEXT, `history` TEXT, `accessToken` TEXT, `refreshToken` TEXT, `deleteToken` UUID, `email` TEXT, `password` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
    2020-07-07T00:00:18.016Z debug: 	Executing (default): INSERT INTO `Users` SELECT `id`, `profileid`, `profile`, `history`, `accessToken`, `refreshToken`, `deleteToken`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users_backup`;
    2020-07-07T00:00:18.016Z debug: 	Executing (default): DROP TABLE `Users_backup`;
    2020-07-07T00:00:18.017Z debug: 	Executing (default): PRAGMA TABLE_INFO(`Users`);
    2020-07-07T00:00:18.017Z debug: 	Executing (default): CREATE TABLE IF NOT EXISTS `Users_backup` (`id` UUID PRIMARY KEY, `profileid` VARCHAR(255), `profile` TEXT, `history` TEXT, `accessToken` TEXT, `refreshToken` TEXT, `deleteToken` UUID, `email` TEXT, `password` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
    2020-07-07T00:00:18.017Z debug: 	Executing (default): INSERT INTO `Users_backup` SELECT `id`, `profileid`, `profile`, `history`, `accessToken`, `refreshToken`, `deleteToken`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users`;
    2020-07-07T00:00:18.018Z debug: 	Executing (default): DROP TABLE `Users`;
    2020-07-07T00:00:18.018Z debug: 	Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`id` UUID PRIMARY KEY, `profileid` VARCHAR(255), `profile` TEXT, `history` TEXT, `accessToken` TEXT, `refreshToken` TEXT, `deleteToken` UUID, `email` TEXT, `password` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
    2020-07-07T00:00:18.019Z debug: 	Executing (default): INSERT INTO `Users` SELECT `id`, `profileid`, `profile`, `history`, `accessToken`, `refreshToken`, `deleteToken`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users_backup`;
    2020-07-07T00:00:18.019Z debug: 	Executing (default): DROP TABLE `Users_backup`;
    2020-07-07T00:00:18.019Z debug: 	Executing (default): CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);
    2020-07-07T00:00:18.020Z debug: 	Executing (default): PRAGMA INDEX_LIST(`SequelizeMeta`)
    2020-07-07T00:00:18.020Z debug: 	Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_SequelizeMeta_1`)
    2020-07-07T00:00:18.020Z debug: 	Executing (default): INSERT INTO `SequelizeMeta` (`name`) VALUES ($1);
    2020-07-07T00:00:18.021Z debug: 	== 20180326103000-use-text-in-tokens: migrated (0.008s)

    2020-07-07T00:00:18.021Z debug: 	Executing (default): CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);
    2020-07-07T00:00:18.021Z debug: 	Executing (default): PRAGMA INDEX_LIST(`SequelizeMeta`)
    2020-07-07T00:00:18.021Z debug: 	Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_SequelizeMeta_1`)
    2020-07-07T00:00:18.022Z debug: 	Executing (default): SELECT `name` FROM `SequelizeMeta` AS `SequelizeMeta` ORDER BY `SequelizeMeta`.`name` ASC;
    2020-07-07T00:00:18.023Z debug: 	== 20180525153000-user-add-delete-token: migrating =======
    2020-07-07T00:00:18.024Z debug: 	Executing (default): ALTER TABLE `Users` ADD `deleteToken` UUID;
    Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: duplicate column name: deleteToken
        at Query.formatError (/home/mhajoha/Projects/codimd/node_modules/sequelize/lib/dialects/sqlite/query.js:422:16)
        at Query._handleQueryResponse (/home/mhajoha/Projects/codimd/node_modules/sequelize/lib/dialects/sqlite/query.js:73:18)
        at afterExecute (/home/mhajoha/Projects/codimd/node_modules/sequelize/lib/dialects/sqlite/query.js:250:31)
        at replacement (/home/mhajoha/Projects/codimd/node_modules/sqlite3/lib/trace.js:25:27)
        at Statement.errBack (/home/mhajoha/Projects/codimd/node_modules/sqlite3/lib/sqlite3.js:14:21)
    ```
    </details>

    If we can fix this problem, I think Umzug would be the best option.

2. Instead of a `config.json`, the [Sequelize CLI also supports a `config.js`](https://sequelize.org/master/manual/migrations.html#dynamic-configuration). We could (probably should) write one which uses `lib/config` to load the necessary configuration values.
