### ISSUE TITLE
codi crashes on login if the oauth2 provider was not configured to supply emails

### ISSUE THREAD

**Issue by Trolldemorted** [hackmdio/codimd#1423]
When using the docker image and not specifying `CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR`, codimd crashes because it always tries to extract an email field:
https://github.com/hackmdio/codimd/blob/6e74e41641dda0d0148cfdad5f7e96ce324e4376/lib/auth/oauth2/index.js#L55

Since there are oauth2 providers that don't disclose an email in their user profiles and codi should not receive emails, send emails or display email adresses, it should not crash if the the email attribute is note supplied.

```
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    | 2020-02-27T12:25:27.579Z error:         uncaughtException: Cannot read property 'split' of undefined
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    | TypeError: Cannot read property 'split' of undefined
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    |     at extractProfileAttribute (/codimd/lib/web/auth/oauth2/index.js:44:15)
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    |     at parseProfile (/codimd/lib/web/auth/oauth2/index.js:55:17)
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    |     at /codimd/lib/web/auth/oauth2/index.js:79:19
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    |     at passBackControl (/codimd/node_modules/oauth/lib/oauth2.js:134:9)
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    |     at IncomingMessage.<anonymous> (/codimd/node_modules/oauth/lib/oauth2.js:157:7)
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    |     at emitNone (events.js:111:20)
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    |     at IncomingMessage.emit (events.js:208:7)
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    |     at endReadableNT (_stream_readable.js:1064:12)
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    |     at process._tickCallback (internal/process/next_tick.js:181:9)
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    | 2020-02-27T12:25:27.579Z error:         An uncaught exception has occured.
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    | 2020-02-27T12:25:27.579Z error:         Cannot read property 'split' of undefined
Feb 27 13:25:27 majorpurpose docker-compose[74148]: codimd_1    | 2020-02-27T12:25:27.579Z error:         Process will exit now.
Feb 27 13:25:28 majorpurpose docker-compose[74148]: codimd_codimd_1 exited with code 1
```

**Comment by a60814billy** [comment]
thanks you for your bug report, we will fix this issue on next release!
