### ISSUE TITLE
Can't build with node LTS 12.16.1

### ISSUE THREAD

**Issue by pkrasicki** [hackmdio/codimd#1445]
Is current LTS version not supported? The [docs](https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-manual-deployment) only mention node versions 8-11. I get this error:

```
./bin/setup
(...)

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.0-8-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/codimd/node_modules/scrypt
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by a60814billy** [comment]
Hi @pkrasicki,
Yes, it currently doesn't support node.js version 12. We're working on it.

**Comment by a60814billy** [comment]
Currently, it is supposed to be Node.JS 10~16. This issue may have been resolved. If it continues to occur, feel free to reopen it.
