### ISSUE TITLE
[hackmd:2.0.1] crash with count note failed

### ISSUE THREAD

**Issue by HaveFun83** [hackmdio/codimd#1516]
Hi we run hackmd 2.0.1 within our k8s cluster after some time the readiness probe fail and the pod is unable the receive traffic.

pod log shows the following error 
```
2020-05-15T08:47:30.313Z error: 	count note failed: SequelizeConnectionAcquireTimeoutError: Operation timeout
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (/home/hackmd/app/node_modules/express/lib/response.js:1123:12)
    at ServerResponse.json (/home/hackmd/app/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/home/hackmd/app/node_modules/express/lib/response.js:158:21)
    at exports.getStatus (/home/hackmd/app/lib/status/index.js:14:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
SequelizeConnectionAcquireTimeoutError: Operation timeout
    at pool.acquire.catch.error (/home/hackmd/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
    at <anonymous>
```
But the liveness probe is running normal
```
2020-05-15T09:36:22.310Z info: 	192.168.0.30 - - [15/May/2020:09:36:22 +0000] "GET /status HTTP/1.1" - - "-" "kube-probe/1.17"
```
Currently only a pod restart fix this issue. But it will came back after some running hours
Any help here?

**Comment by a60814billy** [comment]
Hi @HaveFun83, 

This error is caused by your application can't connect to database. PR #1517 will fixed this error, and return status 500 when any error occurred.

**Comment by a60814billy** [comment]
Hi @HaveFun83, you can update image to `nabo.codimd.dev/hackmdio/hackmd:2.1.0`.

**Comment by HaveFun83** [comment]
@a60814billy thanks for the quick response.
Updated the image today.
