### ISSUE TITLE
Error of deploying hackmd docker container on VM

### ISSUE THREAD

**Issue by jianlianggao** [hackmdio/codimd#933]
Dear dev team,

I am using hackmdio docker compose to deploy hackmd on my Ubuntu 16.04 VM with 2 vCPUs/2GB RAM. I git cloned the hackmdio and ran directly. I got the following errors:
```Creating docker-hackmd_database_1 ... done
Creating docker-hackmd_app_1      ... done
Attaching to docker-hackmd_database_1, docker-hackmd_app_1
database_1  | The files belonging to this database system will be owned by user "postgres".
database_1  | This user must also own the server process.
database_1  | 
database_1  | The database cluster will be initialized with locale "en_US.utf8".
database_1  | The default database encoding has accordingly been set to "UTF8".
database_1  | The default text search configuration will be set to "english".
database_1  | 
database_1  | Data page checksums are disabled.
database_1  | 
database_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
database_1  | creating subdirectories ... ok
database_1  | selecting default max_connections ... 100
database_1  | selecting default shared_buffers ... 128MB
database_1  | selecting dynamic shared memory implementation ... posix
database_1  | creating configuration files ... ok
app_1       | 2018/09/03 11:12:43 Waiting for: tcp://database:5432
app_1       | 2018/09/03 11:12:43 Problem with dial: dial tcp 172.19.0.2:5432: connect: connection refused. Sleeping 1s
database_1  | running bootstrap script ... ok
database_1  | performing post-bootstrap initialization ... sh: locale: not found
database_1  | No usable system locales were found.
database_1  | Use the option "--debug" to see details.
app_1       | 2018/09/03 11:12:44 Problem with dial: dial tcp 172.19.0.2:5432: connect: connection refused. Sleeping 1s
database_1  | ok
database_1  | syncing data to disk ... 
database_1  | WARNING: enabling "trust" authentication for local connections
database_1  | You can change this by editing pg_hba.conf or using the option -A, or
database_1  | --auth-local and --auth-host, the next time you run initdb.
database_1  | ok
database_1  | 
database_1  | Success. You can now start the database server using:
database_1  | 
database_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
database_1  | 
database_1  | waiting for server to start....LOG:  database system was shut down at 2018-09-03 11:12:44 UTC
database_1  | LOG:  MultiXact member wraparound protections are now enabled
database_1  | LOG:  database system is ready to accept connections
database_1  | LOG:  autovacuum launcher started
app_1       | 2018/09/03 11:12:45 Problem with dial: dial tcp 172.19.0.2:5432: connect: connection refused. Sleeping 1s
database_1  |  done
database_1  | server started
database_1  | /usr/local/bin/docker-entrypoint.sh: line 124: cannot create temp file for here-document: Read-only file system
app_1       | 2018/09/03 11:12:46 Problem with dial: dial tcp 172.19.0.2:5432: connect: connection refused. Sleeping 1s
app_1       | 2018/09/03 11:12:48 Connected to tcp://database:5432
app_1       | 
app_1       | Sequelize [Node: 8.11.4, CLI: 2.8.0, ORM: 3.30.4]
app_1       | 
app_1       | Parsed url postgres://hackmd:*****@database:5432/hackmd
app_1       | Unable to connect to database: SequelizeConnectionError: password authentication failed for user "hackmd"
app_1       | 2018-09-03T11:12:53.725Z - warn: Using legacy HMD prefix for environment variables. Please change your variables in future. For details see: https://github.com/hackmdio/codimd#environment-variables-will-overwrite-other-server-configs
app_1       | 2018-09-03T11:12:53.728Z - warn: Session secret not set. Using random generated one. Please set `sessionSecret` in your config.js file. All users will be logged out.
app_1       | Unhandled rejection SequelizeConnectionError: password authentication failed for user "hackmd"
app_1       |     at /hackmd/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:110:20
app_1       |     at Client.<anonymous> (/hackmd/node_modules/pg/lib/client.js:203:5)
app_1       |     at emitOne (events.js:116:13)
app_1       |     at Connection.emit (events.js:211:7)
app_1       |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:133:12)
app_1       |     at emitOne (events.js:116:13)
app_1       |     at Socket.emit (events.js:211:7)
app_1       |     at addChunk (_stream_readable.js:263:12)
app_1       |     at readableAddChunk (_stream_readable.js:250:11)
app_1       |     at Socket.Readable.push (_stream_readable.js:208:10)
app_1       |     at TCP.onread (net.js:597:20)
```
What should I change to make it run successfully?

Many thanks,
Best regards,
J

**Comment by SISheogorath** [comment]
Can you check that your docker-compose file is on the latest version?

https://raw.githubusercontent.com/hackmdio/docker-hackmd/master/docker-compose.yml

It seems like you have read-only containers enabled and may miss some tmpfs settings.

**Comment by jianlianggao** [comment]
Thank you very much. Yes, I did add my ip to the URL and caused the error.
